apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim-dynamic-100
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 90Gi