apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secrets
  namespace: garden-office
type: Opaque
stringData:
  mysql-root-password: "REPLACE_ME_mysql_root_password"
  mysql-password: "REPLACE_ME_mysql_password"
  postgres-password: "REPLACE_ME_postgres_password"
  nextcloud-admin-password: "REPLACE_ME_nextcloud_admin_password"
  jwt-secret: "REPLACE_ME_jwt_secret"
