version: '3'

services:
  postgres:
    image: postgres:13
    container_name: guacamole-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - guacamole-network

  guacd:
    image: guacamole/guacd:latest
    container_name: guacamole-guacd
    restart: always
    networks:
      - guacamole-network
    volumes:
      - drive-data:/drive
      - record-data:/record

  guacamole:
    image: guacamole/guacamole:latest
    container_name: guacamole-client
    depends_on:
      - guacd
      - postgres
    environment:
      GUACD_HOSTNAME: ${GUACD_HOSTNAME}
      GUACD_PORT: ${GUACD_PORT}
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      GUACAMOLE_HOME: /config
      TZ: ${TZ}
    volumes:
      - guacamole-config:/config
    ports:
      - "8080:8080"
    restart: always
    networks:
      - guacamole-network

  # Initialize the PostgreSQL database with Guacamole schema
  # This service runs once and exits
  init-db:
    image: guacamole/guacamole:latest
    container_name: guacamole-init-db
    depends_on:
      - postgres
    environment:
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: ["/opt/guacamole/bin/initdb.sh", "--postgresql"]
    volumes:
      - init-scripts:/tmp/scripts
    networks:
      - guacamole-network

networks:
  guacamole-network:
    driver: bridge

volumes:
  postgres-data:
  drive-data:
  record-data:
  guacamole-config:
  init-scripts:

